/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as AuthHomeIndexImport } from './routes/_auth/home/index'
import { Route as AuthAdministracionUsuariosIndexImport } from './routes/_auth/administracion/usuarios/index'
import { Route as AuthAdministracionPerfilIndexImport } from './routes/_auth/administracion/perfil/index'
import { Route as AuthAdministracionUsuariosCrearUsuarioImport } from './routes/_auth/administracion/usuarios/crear-usuario'
import { Route as AuthAdministracionUsuariosActividadDeUsuariosImport } from './routes/_auth/administracion/usuarios/actividad-de-usuarios'
import { Route as AuthAdministracionUsuariosVerUsuarioRutImport } from './routes/_auth/administracion/usuarios/ver-usuario.$rut'
import { Route as AuthAdministracionUsuariosEditarUsuarioRutImport } from './routes/_auth/administracion/usuarios/editar-usuario.$rut'
import { Route as AuthAdministracionUsuariosActividadDeUsuarioIdImport } from './routes/_auth/administracion/usuarios/actividad-de-usuario.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthHomeIndexRoute = AuthHomeIndexImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAdministracionUsuariosIndexRoute =
  AuthAdministracionUsuariosIndexImport.update({
    id: '/administracion/usuarios/',
    path: '/administracion/usuarios/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionPerfilIndexRoute =
  AuthAdministracionPerfilIndexImport.update({
    id: '/administracion/perfil/',
    path: '/administracion/perfil/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionUsuariosCrearUsuarioRoute =
  AuthAdministracionUsuariosCrearUsuarioImport.update({
    id: '/administracion/usuarios/crear-usuario',
    path: '/administracion/usuarios/crear-usuario',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionUsuariosActividadDeUsuariosRoute =
  AuthAdministracionUsuariosActividadDeUsuariosImport.update({
    id: '/administracion/usuarios/actividad-de-usuarios',
    path: '/administracion/usuarios/actividad-de-usuarios',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionUsuariosVerUsuarioRutRoute =
  AuthAdministracionUsuariosVerUsuarioRutImport.update({
    id: '/administracion/usuarios/ver-usuario/$rut',
    path: '/administracion/usuarios/ver-usuario/$rut',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionUsuariosEditarUsuarioRutRoute =
  AuthAdministracionUsuariosEditarUsuarioRutImport.update({
    id: '/administracion/usuarios/editar-usuario/$rut',
    path: '/administracion/usuarios/editar-usuario/$rut',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthAdministracionUsuariosActividadDeUsuarioIdRoute =
  AuthAdministracionUsuariosActividadDeUsuarioIdImport.update({
    id: '/administracion/usuarios/actividad-de-usuario/$id',
    path: '/administracion/usuarios/actividad-de-usuario/$id',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/home/': {
      id: '/_auth/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthHomeIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/actividad-de-usuarios': {
      id: '/_auth/administracion/usuarios/actividad-de-usuarios'
      path: '/administracion/usuarios/actividad-de-usuarios'
      fullPath: '/administracion/usuarios/actividad-de-usuarios'
      preLoaderRoute: typeof AuthAdministracionUsuariosActividadDeUsuariosImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/crear-usuario': {
      id: '/_auth/administracion/usuarios/crear-usuario'
      path: '/administracion/usuarios/crear-usuario'
      fullPath: '/administracion/usuarios/crear-usuario'
      preLoaderRoute: typeof AuthAdministracionUsuariosCrearUsuarioImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/perfil/': {
      id: '/_auth/administracion/perfil/'
      path: '/administracion/perfil'
      fullPath: '/administracion/perfil'
      preLoaderRoute: typeof AuthAdministracionPerfilIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/': {
      id: '/_auth/administracion/usuarios/'
      path: '/administracion/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AuthAdministracionUsuariosIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/actividad-de-usuario/$id': {
      id: '/_auth/administracion/usuarios/actividad-de-usuario/$id'
      path: '/administracion/usuarios/actividad-de-usuario/$id'
      fullPath: '/administracion/usuarios/actividad-de-usuario/$id'
      preLoaderRoute: typeof AuthAdministracionUsuariosActividadDeUsuarioIdImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/editar-usuario/$rut': {
      id: '/_auth/administracion/usuarios/editar-usuario/$rut'
      path: '/administracion/usuarios/editar-usuario/$rut'
      fullPath: '/administracion/usuarios/editar-usuario/$rut'
      preLoaderRoute: typeof AuthAdministracionUsuariosEditarUsuarioRutImport
      parentRoute: typeof AuthImport
    }
    '/_auth/administracion/usuarios/ver-usuario/$rut': {
      id: '/_auth/administracion/usuarios/ver-usuario/$rut'
      path: '/administracion/usuarios/ver-usuario/$rut'
      fullPath: '/administracion/usuarios/ver-usuario/$rut'
      preLoaderRoute: typeof AuthAdministracionUsuariosVerUsuarioRutImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthHomeIndexRoute: typeof AuthHomeIndexRoute
  AuthAdministracionUsuariosActividadDeUsuariosRoute: typeof AuthAdministracionUsuariosActividadDeUsuariosRoute
  AuthAdministracionUsuariosCrearUsuarioRoute: typeof AuthAdministracionUsuariosCrearUsuarioRoute
  AuthAdministracionPerfilIndexRoute: typeof AuthAdministracionPerfilIndexRoute
  AuthAdministracionUsuariosIndexRoute: typeof AuthAdministracionUsuariosIndexRoute
  AuthAdministracionUsuariosActividadDeUsuarioIdRoute: typeof AuthAdministracionUsuariosActividadDeUsuarioIdRoute
  AuthAdministracionUsuariosEditarUsuarioRutRoute: typeof AuthAdministracionUsuariosEditarUsuarioRutRoute
  AuthAdministracionUsuariosVerUsuarioRutRoute: typeof AuthAdministracionUsuariosVerUsuarioRutRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthHomeIndexRoute: AuthHomeIndexRoute,
  AuthAdministracionUsuariosActividadDeUsuariosRoute:
    AuthAdministracionUsuariosActividadDeUsuariosRoute,
  AuthAdministracionUsuariosCrearUsuarioRoute:
    AuthAdministracionUsuariosCrearUsuarioRoute,
  AuthAdministracionPerfilIndexRoute: AuthAdministracionPerfilIndexRoute,
  AuthAdministracionUsuariosIndexRoute: AuthAdministracionUsuariosIndexRoute,
  AuthAdministracionUsuariosActividadDeUsuarioIdRoute:
    AuthAdministracionUsuariosActividadDeUsuarioIdRoute,
  AuthAdministracionUsuariosEditarUsuarioRutRoute:
    AuthAdministracionUsuariosEditarUsuarioRutRoute,
  AuthAdministracionUsuariosVerUsuarioRutRoute:
    AuthAdministracionUsuariosVerUsuarioRutRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof AuthHomeIndexRoute
  '/administracion/usuarios/actividad-de-usuarios': typeof AuthAdministracionUsuariosActividadDeUsuariosRoute
  '/administracion/usuarios/crear-usuario': typeof AuthAdministracionUsuariosCrearUsuarioRoute
  '/administracion/perfil': typeof AuthAdministracionPerfilIndexRoute
  '/administracion/usuarios': typeof AuthAdministracionUsuariosIndexRoute
  '/administracion/usuarios/actividad-de-usuario/$id': typeof AuthAdministracionUsuariosActividadDeUsuarioIdRoute
  '/administracion/usuarios/editar-usuario/$rut': typeof AuthAdministracionUsuariosEditarUsuarioRutRoute
  '/administracion/usuarios/ver-usuario/$rut': typeof AuthAdministracionUsuariosVerUsuarioRutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/home': typeof AuthHomeIndexRoute
  '/administracion/usuarios/actividad-de-usuarios': typeof AuthAdministracionUsuariosActividadDeUsuariosRoute
  '/administracion/usuarios/crear-usuario': typeof AuthAdministracionUsuariosCrearUsuarioRoute
  '/administracion/perfil': typeof AuthAdministracionPerfilIndexRoute
  '/administracion/usuarios': typeof AuthAdministracionUsuariosIndexRoute
  '/administracion/usuarios/actividad-de-usuario/$id': typeof AuthAdministracionUsuariosActividadDeUsuarioIdRoute
  '/administracion/usuarios/editar-usuario/$rut': typeof AuthAdministracionUsuariosEditarUsuarioRutRoute
  '/administracion/usuarios/ver-usuario/$rut': typeof AuthAdministracionUsuariosVerUsuarioRutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/home/': typeof AuthHomeIndexRoute
  '/_auth/administracion/usuarios/actividad-de-usuarios': typeof AuthAdministracionUsuariosActividadDeUsuariosRoute
  '/_auth/administracion/usuarios/crear-usuario': typeof AuthAdministracionUsuariosCrearUsuarioRoute
  '/_auth/administracion/perfil/': typeof AuthAdministracionPerfilIndexRoute
  '/_auth/administracion/usuarios/': typeof AuthAdministracionUsuariosIndexRoute
  '/_auth/administracion/usuarios/actividad-de-usuario/$id': typeof AuthAdministracionUsuariosActividadDeUsuarioIdRoute
  '/_auth/administracion/usuarios/editar-usuario/$rut': typeof AuthAdministracionUsuariosEditarUsuarioRutRoute
  '/_auth/administracion/usuarios/ver-usuario/$rut': typeof AuthAdministracionUsuariosVerUsuarioRutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/administracion/usuarios/actividad-de-usuarios'
    | '/administracion/usuarios/crear-usuario'
    | '/administracion/perfil'
    | '/administracion/usuarios'
    | '/administracion/usuarios/actividad-de-usuario/$id'
    | '/administracion/usuarios/editar-usuario/$rut'
    | '/administracion/usuarios/ver-usuario/$rut'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/administracion/usuarios/actividad-de-usuarios'
    | '/administracion/usuarios/crear-usuario'
    | '/administracion/perfil'
    | '/administracion/usuarios'
    | '/administracion/usuarios/actividad-de-usuario/$id'
    | '/administracion/usuarios/editar-usuario/$rut'
    | '/administracion/usuarios/ver-usuario/$rut'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/home/'
    | '/_auth/administracion/usuarios/actividad-de-usuarios'
    | '/_auth/administracion/usuarios/crear-usuario'
    | '/_auth/administracion/perfil/'
    | '/_auth/administracion/usuarios/'
    | '/_auth/administracion/usuarios/actividad-de-usuario/$id'
    | '/_auth/administracion/usuarios/editar-usuario/$rut'
    | '/_auth/administracion/usuarios/ver-usuario/$rut'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/home/",
        "/_auth/administracion/usuarios/actividad-de-usuarios",
        "/_auth/administracion/usuarios/crear-usuario",
        "/_auth/administracion/perfil/",
        "/_auth/administracion/usuarios/",
        "/_auth/administracion/usuarios/actividad-de-usuario/$id",
        "/_auth/administracion/usuarios/editar-usuario/$rut",
        "/_auth/administracion/usuarios/ver-usuario/$rut"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/home/": {
      "filePath": "_auth/home/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/actividad-de-usuarios": {
      "filePath": "_auth/administracion/usuarios/actividad-de-usuarios.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/crear-usuario": {
      "filePath": "_auth/administracion/usuarios/crear-usuario.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/perfil/": {
      "filePath": "_auth/administracion/perfil/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/": {
      "filePath": "_auth/administracion/usuarios/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/actividad-de-usuario/$id": {
      "filePath": "_auth/administracion/usuarios/actividad-de-usuario.$id.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/editar-usuario/$rut": {
      "filePath": "_auth/administracion/usuarios/editar-usuario.$rut.tsx",
      "parent": "/_auth"
    },
    "/_auth/administracion/usuarios/ver-usuario/$rut": {
      "filePath": "_auth/administracion/usuarios/ver-usuario.$rut.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
