/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AdministracionDashboardImport } from './routes/administracion/dashboard'
import { Route as AdministracionUsuariosIndexImport } from './routes/administracion/usuarios/index'

// Create/Update Routes

const AdministracionDashboardRoute = AdministracionDashboardImport.update({
  id: '/administracion/dashboard',
  path: '/administracion/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const AdministracionUsuariosIndexRoute =
  AdministracionUsuariosIndexImport.update({
    id: '/administracion/usuarios/',
    path: '/administracion/usuarios/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/administracion/dashboard': {
      id: '/administracion/dashboard'
      path: '/administracion/dashboard'
      fullPath: '/administracion/dashboard'
      preLoaderRoute: typeof AdministracionDashboardImport
      parentRoute: typeof rootRoute
    }
    '/administracion/usuarios/': {
      id: '/administracion/usuarios/'
      path: '/administracion/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AdministracionUsuariosIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/administracion/dashboard': typeof AdministracionDashboardRoute
  '/administracion/usuarios': typeof AdministracionUsuariosIndexRoute
}

export interface FileRoutesByTo {
  '/administracion/dashboard': typeof AdministracionDashboardRoute
  '/administracion/usuarios': typeof AdministracionUsuariosIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/administracion/dashboard': typeof AdministracionDashboardRoute
  '/administracion/usuarios/': typeof AdministracionUsuariosIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/administracion/dashboard' | '/administracion/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/administracion/dashboard' | '/administracion/usuarios'
  id: '__root__' | '/administracion/dashboard' | '/administracion/usuarios/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AdministracionDashboardRoute: typeof AdministracionDashboardRoute
  AdministracionUsuariosIndexRoute: typeof AdministracionUsuariosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AdministracionDashboardRoute: AdministracionDashboardRoute,
  AdministracionUsuariosIndexRoute: AdministracionUsuariosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/administracion/dashboard",
        "/administracion/usuarios/"
      ]
    },
    "/administracion/dashboard": {
      "filePath": "administracion/dashboard.tsx"
    },
    "/administracion/usuarios/": {
      "filePath": "administracion/usuarios/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
